name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  restore_build:
    name: Restore Dependencies, Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore Identity.API.csproj

      - name: Build Project
        run: dotnet build Identity.API.csproj

  deploy:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: [restore_build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build Image
        run: docker build . -t ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}:latest

      - name: Push Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}:latest

      - name: Connect to VM with SSH, update and run docker containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/azureuser/home/baim/identity
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
